dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: sincere-actor-393814
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_dw') }}"
      threads: 4
      keyfile: C:\Users\marcell.oliveira\.dbt\sincere-actor-393814-82a61d0a595b.json
              